### PR TITLE
Embeddable and Embedded

### PR DESCRIPTION
**Pull request by millergarym**
## Embeddable
Exposed `modtmpl.ProcessFile` so that md-tmpl can be embedded in another executable.
eg 
``` go
	proc := modtmpl.NewProcessor()
	proc.Write = true
	proc.ProcessFile(eg, path.Join(eg, "README.md"))
```

## Embedded
In doing this came up with a missing use-case for opts that of distributed embedded structs.
`opts.New(&root).Name("md-tmpl").EmbedStruct(proc).Parse()`

Almost created an illegal circular dependency between opts and md-tmpl.
md-tmpl depends on opts &
opts/examples depends on md-tmpl.

### CODE REVIEW

**Comment by jpillora** [comment]
Thanks Gary though I think the programmatic API should be different to the CLI API:

```
Commands(md []byte) ([]string, error)
Execute(md []byte) ([]byte, error)
```

File handling only done in user packages.

Also, `mod` ? Package name should be `mdtmpl` (or `markdowntmpl` but that's a bit long)

**Comment by millergarym** [comment]
> Also, mod ? Package name should be mdtmpl (or markdowntmpl but that's a bit long)
Ahh, `mod` was for `modification`, I have read `md` as `mk` as in `make`.

What is a CLI API, the api used by the cli?
If so then how should they be different?

I agree the public API isn't great. I was going for a small PR.

```
type Processor interface {
	ProcessFile(workingDir, file string) error
}
```
is better than
```
func (config *processor) ProcessFile(wd, file string) 
```

This introduces other complexities.

**Comment by jpillora** [comment]
> Ahh, mod was for modification, I have read md as mk as in make.

Now I think about it, this package should actually be called something like `shtmpl` (shell templates) and execute arbitrary shell in any file type using various types of code comments

> What is a CLI API, the api used by the cli?

Sorry my mistake, just "CLI" (command-line interface), so the Go API should be something simple like:

```go
Commands(md []byte) ([]string, error)
Execute(md []byte) ([]byte, error)
```

and then the CLI should do the file handling (`iotuil`.`Read`/`Write` `File`), and then use the new Go API to maintain current behaviour.

Once this is in, then the `opts/example` package can just use the `Execute` function.

> I was going for a small PR.

This change is mostly moves and renames, shouldn't be any extra logic so should be small. I'll can try to get to it this week, though might be short for time!

**Comment by jpillora** [comment]
Resolved in #17c7a8b, will manually merge your opts PR using this :+1:

**Pull request closed without merging**
